# Pure explosion baseline (FAST): Central BH explodes with NO orbiting tugboats
# This tests what happens WITHOUT the Ring 0 gravitational tugboat mechanism.
# Expected: debris should fall back due to self-gravity (no mechanism to prevent collapse)
# OPTIMIZED: 100 particles for faster physics validation (~5 min vs 8+ hours)

simulation_name: "pure_explosion_fast"
output_directory: "./results/pure_explosion_fast"

# Central black hole that explodes at t=0
# REDUCED by 1000x to test if over-acceleration from massive particles is the issue
central_black_hole:
  mass_solar_masses: 4.0e+19  # Was 4.0e+22, reduced by 1000x

# Ring 0: NO tugboats - this is the control case
ring_0:
  count: 0
  radius_gly: 14.0  # Not used (count=0)
  mass_per_bh_solar_masses: 1.0e+21
  velocity_mode: "keplerian"
  capture_radius_gly: 0.5

# Rings 1-3: Also disabled for pure explosion test
ring_1:
  count: 0
  radius_gly: 100.0
  mass_per_bh_solar_masses: 5.0e+21
  velocity_mode: "keplerian"
  is_static: false

ring_2:
  count: 0
  radius_gly: 150.0
  mass_per_bh_solar_masses: 1.0e+22
  velocity_mode: "keplerian"
  is_static: false

ring_3:
  count: 0
  radius_gly: 200.0
  mass_per_bh_solar_masses: 1.5e+22
  velocity_mode: "keplerian"
  is_static: false

# Debris field: Explosion products (REDUCED to 100 particles)
# HIGH SPEED to separate quickly and avoid close-range catastrophic forces
debris_field:
  particle_count: 100
  position_min_gly: 0.01   # Very close to center (10 Mly)
  position_max_gly: 0.1    # Out to 100 Mly
  velocity_min_fraction_c: 0.9     # Very fast particles
  velocity_max_fraction_c: 0.999   # Near light speed
  distribution: "uniform"

# Simulation control
simulation_control:
  timestep_gyr: 0.001       # 1 Myr timestep
  duration_gyr: 100.0       # 100 Gyr total
  output_interval_gyr: 1.0  # Save every 1 Gyr (100 snapshots)
  checkpoint_interval_gyr: 10.0  # Checkpoint every 10 Gyr

# Physics options
physics_options:
  force_method: "direct"
  use_newtonian_enhancements: false
  barnes_hut:
    opening_angle_theta: 0.5
    max_particles_per_leaf: 8
    tree_rebuild_interval: 10

# Logging and diagnostics
diagnostics:
  check_energy_conservation: true
  check_momentum_conservation: true
  log_level: "INFO"
